export interface LeadershipPrinciple {
  id: number;
  title: string;
  verse: string;
  verseText: string;
  devotional: string;
  challenge: string;
  tag: string;
}

export const LEADERSHIP_PRINCIPLES: LeadershipPrinciple[] = [
  {
    id: 1,
    title: "Serve Before You Lead",
    verse: "Matthew 20:26-28 (NLT)",
    verseText: "Whoever wants to be a leader among you must be your servant, and whoever wants to be first among you must become your slave. For even the Son of Man came not to be served but to serve others.",
    devotional: "The world's model of leadership is about getting to the top. Jesus flipped it. He said the greatest person in the room is the one doing the most for everyone else. That's not weakness — that's the most powerful kind of influence there is.\n\nBefore you worry about whether your students are listening to you, ask yourself: are you serving them? Do they know you genuinely care about their lives outside of Monday nights? People follow leaders who serve them, not leaders who perform for them.",
    challenge: "This week, do one thing for one of your students that they would never expect from a leader. Not because it's your job. Because you're a servant first.",
    tag: "Foundation",
  },
  {
    id: 2,
    title: "Know Your People By Name",
    verse: "John 10:3 (NLT)",
    verseText: "He calls his own sheep by name and leads them out.",
    devotional: "Jesus doesn't lead in the abstract. He knows names. He knows faces. He knows stories. That's the standard for every leader who follows Him.\n\nYou can give a great Bible study and still miss the person sitting in front of you. The coach who remembers a kid's name, asks about the game, knows what's going on at home — that's the one they'll actually talk to when things get real.",
    challenge: "Before your next session, write down every student's name. Next to each name, write one thing you know about their life right now. If you can't — that's your homework.",
    tag: "People",
  },
  {
    id: 3,
    title: "Stay Connected to the Source",
    verse: "John 15:4-5 (NLT)",
    verseText: "Remain in me, and I will remain in you. For a branch cannot produce fruit if it is severed from the vine. Yes, apart from me you can do nothing.",
    devotional: "You cannot give what you don't have. If you're not staying connected to God yourself — through prayer, Scripture, quiet time — you will run dry. You'll start going through the motions and your students will feel it.\n\nThe most dangerous thing for a leader is looking productive while being disconnected. You can lead a Bible study without actually being in the Word yourself. But it shows. Stay plugged in.",
    challenge: "Block 10 minutes every day this week — not to prep the study, but just to be with God. No agenda. Just stay connected.",
    tag: "Spiritual Health",
  },
  {
    id: 4,
    title: "Prepare Before You Lead",
    verse: "Ezra 7:10 (NLT)",
    verseText: "Ezra had determined to study and obey the Law of the Lord and to teach those decrees and regulations to the people of Israel.",
    devotional: "Ezra did three things in order: study, obey, then teach. He didn't skip steps. He didn't lead something he hadn't lived himself first. That's the pattern God honors.\n\nWhen you prepare for Monday night, don't just prep the content. Sit with the material personally. Let it hit you first. If the Big Idea doesn't land on your own life before it lands on your students, you're delivering a package you haven't opened.",
    challenge: "Before your next study, spend 15 minutes on just one question: how does this Big Idea apply to your life right now? Be honest with yourself. Then lead from that place.",
    tag: "Preparation",
  },
  {
    id: 5,
    title: "Pray for Those You Lead",
    verse: "Colossians 1:9 (NLT)",
    verseText: "We have not stopped praying for you since we first heard about you.",
    devotional: "Paul never stopped praying for the people he led. Not just before he saw them. Consistently. By name. With specific requests. That's not just a devotional habit — it's a leadership discipline.\n\nWhen you pray for your students by name before you see them on Monday, something shifts. You walk in differently. You look at them differently. Prayer moves you from seeing students as an audience to seeing them as people God entrusted to you.",
    challenge: "Set an alarm for every day this week labeled with one student's name. When it goes off, pray for that student specifically. Rotate through your group.",
    tag: "Prayer",
  },
  {
    id: 6,
    title: "Handle Conflict Directly",
    verse: "Matthew 18:15 (NLT)",
    verseText: "If another believer sins against you, go privately and point out the offense. If the other person listens and confesses it, you have won that person back.",
    devotional: "Most leadership problems don't get resolved — they get avoided. Jesus gave a clear process: go directly, go privately, go with the goal of restoration. Not exposure. Not venting to others. Not passive-aggressively hoping it fixes itself.\n\nAs a leader, how you handle conflict is one of the most visible things your students watch. If you deal with it honestly and humbly, you teach them to do the same.",
    challenge: "Is there a conversation you've been avoiding? Have it this week. Go directly, go privately, go for restoration.",
    tag: "Conflict",
  },
  {
    id: 7,
    title: "Guard Your Own Heart First",
    verse: "Proverbs 4:23 (NLT)",
    verseText: "Guard your heart above all else, for it determines the course of your life.",
    devotional: "You can't lead people to places you haven't protected yourself. What you let into your own heart — what you're watching, listening to, spending time on — shapes what comes out of you on Monday night. You can't fake health indefinitely.\n\nLeadership starts on the inside. The condition of your heart determines the direction of your leadership. Guard it intentionally.",
    challenge: "Do an honest audit this week. What's getting the most of your attention? Is it making you more like the leader you want to be, or less?",
    tag: "Character",
  },
  {
    id: 8,
    title: "Speak Life, Not Death",
    verse: "Proverbs 18:21 (NLT)",
    verseText: "The tongue can bring death or life; those who love to talk will reap the consequences.",
    devotional: "Your words as a leader carry more weight than you know. A single sentence at the right moment can change the trajectory of a student's life. A careless word can do real damage that lasts years.\n\nThis doesn't mean you only say nice things. It means you're intentional. You think before you speak. You ask yourself: will this build this person up or tear them down? Correction can be life-giving when it's delivered with love and purpose.",
    challenge: "This week, say something specific and true to each student — something you genuinely see in them. Not generic encouragement. Something real.",
    tag: "Communication",
  },
  {
    id: 9,
    title: "Stay Teachable",
    verse: "Proverbs 9:9 (NLT)",
    verseText: "Instruct the wise, and they will be even wiser. Teach the righteous, and they will learn even more.",
    devotional: "The moment you think you've arrived as a leader, you stop growing. The best leaders are always the most teachable people in the room. They listen more than they talk. They're genuinely open to correction. They don't protect their ego at the expense of their growth.\n\nYou're going to make mistakes leading these students. The question isn't whether you'll get it wrong — it's whether you'll learn from it or defend it.",
    challenge: "Ask someone you trust for honest feedback on your leadership this week. Not what you're doing well. What could be better. Then actually listen.",
    tag: "Growth",
  },
  {
    id: 10,
    title: "Don't Lead Alone",
    verse: "Ecclesiastes 4:9-10 (NLT)",
    verseText: "Two people are better off than one, for they can help each other succeed. If one person falls, the other can reach out and help.",
    devotional: "Isolated leadership is dangerous leadership. When you don't have anyone speaking into you, your blind spots stay blind. When you don't have anyone checking on you, your own struggles go unaddressed. And a struggling leader can't fully serve struggling students.\n\nFind your people. Another coach. A mentor. Someone who can ask you the hard questions and tell you the truth. You were never designed to do this alone.",
    challenge: "Who is the person speaking into your leadership right now? If no one comes to mind, that's your first assignment. Reach out this week.",
    tag: "Community",
  },
  {
    id: 11,
    title: "Model What You Teach",
    verse: "Philippians 4:9 (NLT)",
    verseText: "Keep putting into practice all you learned and received from me — everything you heard from me and saw me doing. Then the God of peace will be with you.",
    devotional: "Paul said watch what I do, not just what I say. That's a bold thing to say — and it should be the standard for every leader. Your students are watching you more closely than you think. How you handle pressure, how you treat people, how you respond when things don't go your way.\n\nYour life is the most powerful thing you bring to Monday nights. It either confirms or undermines everything you say.",
    challenge: "Pick one thing you taught in a recent study. How are you personally living it right now? Be honest. Then close the gap.",
    tag: "Integrity",
  },
  {
    id: 12,
    title: "Be Honest About Your Struggles",
    verse: "James 5:16 (NLT)",
    verseText: "Confess your sins to each other and pray for each other so that you may be healed.",
    devotional: "Vulnerability is one of the most powerful tools a leader has. When you are honest about your own failures and struggles — appropriately, not as confession to your students but as real humanity — it gives everyone else permission to be honest too.\n\nYou don't have to have it all together to lead. You just have to be real. Students can spot a performance from a mile away. They respond to authenticity.",
    challenge: "In your next session, share one area of your own life where you're genuinely working on something. Not as a performance of humility. As a real moment of honesty.",
    tag: "Authenticity",
  },
  {
    id: 13,
    title: "Rest Is Not Weakness",
    verse: "Mark 6:31 (NLT)",
    verseText: "Jesus said, 'Let's go off by ourselves to a quiet place and rest awhile.' He said this because there were so many people coming and going that Jesus and his apostles didn't even have time to eat.",
    devotional: "Jesus built rest into His leadership. He didn't treat it as a luxury or a sign of weakness — He treated it as a necessity. A depleted leader leads poorly. You can push through for a while, but eventually the tank is empty and the people around you pay the price.\n\nResting on purpose is not laziness. It's stewardship of the energy and health God gave you to lead with.",
    challenge: "Block one hour this week that belongs only to you — no prep, no texts, no hustle. Just rest. Protect it like an appointment.",
    tag: "Health",
  },
  {
    id: 14,
    title: "Your Character Is Your Credibility",
    verse: "1 Timothy 4:12 (NLT)",
    verseText: "Don't let anyone think less of you because you are young. Be an example to all believers in what you say, in the way you live, in your love, your faith, and your purity.",
    devotional: "You don't earn the right to lead through titles or talent — you earn it through character. Who you are in private, in hard moments, in small things — that's what actually gives you influence with people.\n\nCharacter is built slowly and lost quickly. Protect it. Every small decision you make is either strengthening or weakening your credibility as a leader.",
    challenge: "Think about the last 7 days. Was there a moment where your character was tested and you chose well? And one where you could have done better? Learn from both.",
    tag: "Character",
  },
  {
    id: 15,
    title: "God Grows Leaders Through Hard Seasons",
    verse: "James 1:2-4 (NLT)",
    verseText: "When troubles of any kind come your way, consider it an opportunity for great joy. For you know that when your faith is tested, your endurance has a chance to grow.",
    devotional: "The leaders God uses most are the ones who went through the hardest things and didn't quit. Not the ones with the most talent or the smoothest path. The hard seasons aren't obstacles to your leadership — they're the training ground for it.\n\nWhat you're walking through right now, personally — the difficulty, the uncertainty, the waiting — is not wasted. God is developing something in you that can only be built under pressure.",
    challenge: "What hard season are you in right now? Write down one thing you believe God is growing in you through it. Sit with that.",
    tag: "Growth",
  },
  {
    id: 16,
    title: "Lead with Consistency",
    verse: "1 Corinthians 11:1 (NLT)",
    verseText: "And you should imitate me, just as I imitate Christ.",
    devotional: "Consistency is one of the rarest and most powerful things in a leader. Being the same person on Monday night as you are on Tuesday morning. Showing up the same way whether five students came or twenty. Treating every student the same whether they're all-stars or struggling.\n\nPeople follow consistent leaders because they're safe. They know what they're getting. They trust you because you're the same yesterday and today.",
    challenge: "Where are you inconsistent right now? Pick one area — energy, preparation, how you treat certain students — and commit to showing up consistently there this week.",
    tag: "Foundation",
  },
  {
    id: 17,
    title: "Seek Wisdom Before Acting",
    verse: "Proverbs 15:22 (NLT)",
    verseText: "Plans go wrong for lack of advice; many advisers bring success.",
    devotional: "Quick decisions and lone-wolf leadership get leaders into trouble. The wisest leaders don't assume they have all the answers — they actively seek input before they act. They have people they call. They pray before they move. They ask questions before they make calls.\n\nHumility in decision-making isn't slow. It's smart. And it keeps you from the kind of mistakes that damage relationships and undermine your leadership.",
    challenge: "Before your next big leadership decision — however small it seems — ask one other person for their honest read on it. Don't just inform them. Actually ask.",
    tag: "Wisdom",
  },
  {
    id: 18,
    title: "Celebrate Others Wins",
    verse: "Romans 12:15 (NLT)",
    verseText: "Be happy with those who are happy, and weep with those who weep.",
    devotional: "Great leaders make others feel seen and celebrated. When a student has a win — on the field, in the classroom, in their personal life — stop and acknowledge it. When they're hurting, sit in it with them instead of rushing to fix it.\n\nYour ability to enter into someone else's moment — joy or pain — without making it about you is one of the highest forms of leadership.",
    challenge: "This week, celebrate something specific about one student in front of the group. Make it real and earned, not generic. Watch what it does to the room.",
    tag: "People",
  },
  {
    id: 19,
    title: "The Best Leaders Are the Best Followers",
    verse: "Luke 16:10 (NLT)",
    verseText: "If you are faithful in little things, you will be faithful in large ones.",
    devotional: "You lead others at the level you follow well yourself. How you respond to authority — to your own coaches, mentors, and to God — directly shapes how the people under you respond to you.\n\nFaithfulness in small things is the proving ground for bigger leadership. The way you treat Monday nights when attendance is low, when you're tired, when it seems like nobody cares — that's where your actual character as a leader is revealed.",
    challenge: "Where are you being trusted with something small right now? Are you treating it like it matters? Because it does.",
    tag: "Foundation",
  },
  {
    id: 20,
    title: "Cast Vision Clearly",
    verse: "Habakkuk 2:2 (NLT)",
    verseText: "Write my answer plainly on tablets, so that a runner can carry the correct message to others.",
    devotional: "People move toward what they can see clearly. As a leader, your job is to paint a picture of where you're going and why it matters — simply enough that anyone can carry it. If you can't say what you're building in one sentence, your people can't either.\n\nFor Triple F, the vision is clear: we're growing athletes who know who they are, how to serve, and who they belong to. Make sure every student in the room knows that's what Monday nights are for.",
    challenge: "Can you say what you're building with this group in one sentence? Write it down. If it takes more than two sentences, simplify until it doesn't.",
    tag: "Vision",
  },
];

export const DAILY_VERSES = [
  { ref: "Proverbs 27:17 (NLT)", text: "As iron sharpens iron, so a friend sharpens a friend." },
  { ref: "Joshua 1:9 (NLT)", text: "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go." },
  { ref: "Micah 6:8 (NLT)", text: "Act justly, love mercy, and walk humbly with your God." },
  { ref: "Matthew 5:16 (NLT)", text: "Let your good deeds shine out for all to see, so that everyone will praise your heavenly Father." },
  { ref: "1 Timothy 4:8 (NLT)", text: "Physical training is good, but training for godliness is much better." },
  { ref: "Colossians 3:23 (NLT)", text: "Work willingly at whatever you do, as though you were working for the Lord rather than for people." },
  { ref: "Romans 5:3-4 (NLT)", text: "We can rejoice when we run into problems and trials, for we know that they help us develop endurance, and endurance develops strength of character." },
  { ref: "2 Timothy 1:7 (NLT)", text: "God has not given us a spirit of fear and timidity, but of power, love, and self-discipline." },
  { ref: "Isaiah 40:31 (NLT)", text: "Those who trust in the Lord will find new strength. They will soar high on wings like eagles." },
  { ref: "Philippians 4:13 (NLT)", text: "I can do everything through Christ, who gives me strength." },
  { ref: "James 1:5 (NLT)", text: "If you need wisdom, ask our generous God, and he will give it to you." },
  { ref: "Proverbs 3:5-6 (NLT)", text: "Trust in the Lord with all your heart; do not depend on your own understanding. Seek his will in all you do, and he will show you which path to take." },
  { ref: "1 Corinthians 9:25 (NLT)", text: "All athletes are disciplined in their training. They do it to win a prize that will fade away, but we do it for an eternal prize." },
  { ref: "Galatians 6:9 (NLT)", text: "Don't be discouraged and give up, for we will reap a harvest of blessing at the appropriate time." },
  { ref: "Hebrews 12:1 (NLT)", text: "Let us strip off every weight that slows us down and run with endurance the race God has set before us." },
  { ref: "Mark 10:43-44 (NLT)", text: "Whoever wants to be a leader among you must be your servant, and whoever wants to be first among you must be the slave of everyone else." },
  { ref: "Psalm 119:105 (NLT)", text: "Your word is a lamp to guide my feet and a light for my path." },
  { ref: "Ephesians 4:2 (NLT)", text: "Always be humble and gentle. Be patient with each other, making allowance for each other's faults because of your love." },
  { ref: "1 Peter 5:2-3 (NLT)", text: "Care for the flock that God has entrusted to you. Lead them not by force but by example." },
  { ref: "Romans 8:28 (NLT)", text: "We know that God causes everything to work together for the good of those who love God." },
  { ref: "Jeremiah 29:11 (NLT)", text: "I know the plans I have for you, says the Lord. They are plans for good and not for disaster, to give you a future and a hope." },
  { ref: "Psalm 23:1 (NLT)", text: "The Lord is my shepherd; I have all that I need." },
  { ref: "Matthew 6:33 (NLT)", text: "Seek the Kingdom of God above all else, and live righteously, and he will give you everything you need." },
  { ref: "2 Corinthians 12:9 (NLT)", text: "My grace is sufficient for you, for my power is made perfect in weakness." },
  { ref: "Proverbs 22:6 (NLT)", text: "Direct your children onto the right path, and when they are older, they will not leave it." },
  { ref: "Ezekiel 34:16 (NLT)", text: "I will search for my lost ones who strayed away, and I will bring them safely home again." },
  { ref: "1 Samuel 16:7 (NLT)", text: "The Lord doesn't see things the way you see them. People judge by outward appearance, but the Lord looks at the heart." },
  { ref: "Philippians 2:3 (NLT)", text: "Don't be selfish; don't try to impress others. Be humble, thinking of others as better than yourselves." },
  { ref: "Luke 9:23 (NLT)", text: "If any of you wants to be my follower, you must give up your own way, take up your cross daily, and follow me." },
  { ref: "John 13:35 (NLT)", text: "Your love for one another will prove to the world that you are my disciples." },
];
